server:
  port: 8980
spring:
  application:
    name: spark-control
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@localhost:8761/eureka/
  instance:
    prefer‐ip‐address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
eurekaUserName: spark
eurekaPassWord: spark


management:
  endpoints:
    web:
      exposure:
        include: "*"